"""No real program ever launches in these tests - subprocess.Popen and
os.startfile are mocked throughout, and _list_start_apps (which would shell
out to PowerShell for real) is always mocked with canned data."""

import asyncio
from unittest.mock import patch

from app.domains.computer import KNOWN_APPS, _find_installed_app, register
from app.tools.registry import ToolRegistry, TurnContext

_FAKE_START_APPS = [
    {"Name": "Steam", "AppID": r"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\Steam.exe"},
    {"Name": "Blender", "AppID": "steam://rungameid/365670"},
    {"Name": "Developer PowerShell for VS 2022", "AppID": "Microsoft.AutoGenerated.{some-guid}"},
    {"Name": "Git Bash", "AppID": "Microsoft.AutoGenerated.{other-guid}"},
]


def make_registry() -> ToolRegistry:
    registry = ToolRegistry()
    register(registry)
    return registry


def test_registers_exactly_one_tool():
    registry = make_registry()
    names = [t.name for t in registry.definitions()]
    assert names == ["open_application"]


def test_opens_known_app_by_exact_name():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.subprocess.Popen") as mock_popen:
        result = asyncio.run(registry.dispatch("open_application", {"app": "notepad"}, ctx))

    mock_popen.assert_called_once_with(["notepad.exe"])
    assert result == {"ok": True, "opened": "notepad"}
    assert "notepad" in ctx.touched


def test_matching_is_case_insensitive():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.subprocess.Popen") as mock_popen:
        asyncio.run(registry.dispatch("open_application", {"app": "Calculator"}, ctx))

    mock_popen.assert_called_once_with(["calc.exe"])


def test_known_app_with_a_file_path_opens_that_file_directly(tmp_path):
    """This is the actual fix for a reported bug: 'open notepad and write
    hello world' wrote hello.txt but then opened a blank Notepad unrelated
    to it - passing file lets the two tool calls actually connect."""
    written_file = tmp_path / "hello.txt"
    written_file.write_text("привет мира", encoding="utf-8")
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.subprocess.Popen") as mock_popen:
        result = asyncio.run(
            registry.dispatch("open_application", {"app": "notepad", "file": str(written_file)}, ctx)
        )

    mock_popen.assert_called_once_with(["notepad.exe", str(written_file)])
    assert result == {"ok": True, "opened": "notepad"}


def test_known_app_with_a_missing_file_path_errors_without_launching(tmp_path):
    missing_file = tmp_path / "does_not_exist.txt"
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.subprocess.Popen") as mock_popen:
        result = asyncio.run(
            registry.dispatch("open_application", {"app": "notepad", "file": str(missing_file)}, ctx)
        )

    assert "error" in result
    mock_popen.assert_not_called()


def test_russian_alias_resolves_to_same_executable():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.subprocess.Popen") as mock_popen:
        asyncio.run(registry.dispatch("open_application", {"app": "блокнот"}, ctx))

    mock_popen.assert_called_once_with(["notepad.exe"])


def test_browser_alias_with_no_url_launches_the_real_default_browser(tmp_path):
    fake_browser = tmp_path / "librewolf.exe"
    fake_browser.write_text("")  # just needs to exist for os.path.exists
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._default_browser_executable", return_value=str(fake_browser)),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
        patch("app.domains.computer.os.startfile") as mock_startfile,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "browser"}, ctx))

    mock_popen.assert_called_once_with([str(fake_browser)])
    mock_startfile.assert_not_called()
    assert result == {"ok": True, "opened": "browser"}


def test_browser_alias_falls_back_to_a_url_if_default_browser_cannot_be_found():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._default_browser_executable", return_value=None),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
        patch("app.domains.computer.os.startfile") as mock_startfile,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "browser"}, ctx))

    mock_popen.assert_not_called()
    mock_startfile.assert_called_once()
    assert result == {"ok": True, "opened": "browser"}


def test_browser_with_bare_site_name_gets_https_prefix():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.os.startfile") as mock_startfile:
        result = asyncio.run(
            registry.dispatch("open_application", {"app": "browser", "url": "youtube.com"}, ctx)
        )

    mock_startfile.assert_called_once_with("https://youtube.com")
    assert result == {"ok": True, "opened": "browser", "url": "https://youtube.com"}


def test_browser_with_full_url_passed_through_unchanged():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.os.startfile") as mock_startfile:
        asyncio.run(
            registry.dispatch(
                "open_application", {"app": "browser", "url": "http://example.com/page"}, ctx
            )
        )

    mock_startfile.assert_called_once_with("http://example.com/page")


def test_russian_browser_alias_supports_url_too():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.os.startfile") as mock_startfile:
        asyncio.run(
            registry.dispatch("open_application", {"app": "браузер", "url": "youtube.com"}, ctx)
        )

    mock_startfile.assert_called_once_with("https://youtube.com")


def test_non_http_scheme_url_is_rejected():
    registry = make_registry()
    ctx = TurnContext()
    with patch("app.domains.computer.os.startfile") as mock_startfile:
        result = asyncio.run(
            registry.dispatch("open_application", {"app": "browser", "url": "file:///C:/secrets.txt"}, ctx)
        )

    mock_startfile.assert_not_called()
    assert "error" in result


def test_blocked_app_name_rejected_before_ever_calling_get_start_apps():
    """cmd is blocked by keyword alone - must never even shell out to
    PowerShell to look it up."""
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
        patch("app.domains.computer.os.startfile") as mock_startfile,
        patch("app.domains.computer._list_start_apps") as mock_list_apps,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "cmd"}, ctx))

    assert "error" in result
    mock_popen.assert_not_called()
    mock_startfile.assert_not_called()
    mock_list_apps.assert_not_called()
    assert ctx.touched == set()


def test_shell_and_terminal_apps_are_never_in_the_fast_path_allowlist():
    for shell_name in ("cmd", "powershell", "bash", "wsl", "terminal", "sh", "cmd.exe", "powershell.exe"):
        assert shell_name not in KNOWN_APPS


# --- generic lookup via Get-StartApps, for anything not in KNOWN_APPS ---


def test_generic_app_found_by_exact_name_launches_via_apps_folder():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._list_start_apps", return_value=_FAKE_START_APPS),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "Steam"}, ctx))

    mock_popen.assert_called_once_with(
        ["explorer.exe", r"shell:AppsFolder\{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\Steam.exe"]
    )
    assert result == {"ok": True, "opened": "Steam"}
    assert "Steam" in ctx.touched


def test_generic_app_found_by_case_insensitive_substring():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._list_start_apps", return_value=_FAKE_START_APPS),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "steam"}, ctx))

    mock_popen.assert_called_once()
    assert result["opened"] == "Steam"


def test_generic_lookup_no_match_returns_error_without_launching():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._list_start_apps", return_value=_FAKE_START_APPS),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "some nonexistent app xyz"}, ctx))

    assert "error" in result
    mock_popen.assert_not_called()


def test_generic_lookup_still_blocks_matched_shell_apps():
    """Even if fuzzy-matched via Get-StartApps, a blocked name is rejected -
    this is the exact scenario the blocklist exists for, since Get-StartApps
    genuinely lists things like 'Developer PowerShell for VS 2022'."""
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._list_start_apps", return_value=_FAKE_START_APPS),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
    ):
        result = asyncio.run(
            registry.dispatch("open_application", {"app": "developer powershell for vs 2022"}, ctx)
        )

    assert "error" in result
    mock_popen.assert_not_called()


def test_generic_lookup_blocks_git_bash():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer._list_start_apps", return_value=_FAKE_START_APPS),
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
    ):
        result = asyncio.run(registry.dispatch("open_application", {"app": "git bash"}, ctx))

    assert "error" in result
    mock_popen.assert_not_called()


def test_find_installed_app_prefers_exact_match_over_substring(monkeypatch):
    apps = [
        {"Name": "Steam", "AppID": "exact-id"},
        {"Name": "Steam Support Center", "AppID": "substring-id"},
    ]
    monkeypatch.setattr("app.domains.computer._list_start_apps", lambda: apps)

    match = _find_installed_app("Steam")

    assert match["AppID"] == "exact-id"


def test_known_apps_take_priority_and_never_call_get_start_apps():
    registry = make_registry()
    ctx = TurnContext()
    with (
        patch("app.domains.computer.subprocess.Popen") as mock_popen,
        patch("app.domains.computer._list_start_apps") as mock_list_apps,
    ):
        asyncio.run(registry.dispatch("open_application", {"app": "notepad"}, ctx))

    mock_popen.assert_called_once_with(["notepad.exe"])
    mock_list_apps.assert_not_called()
